import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Theme, Box, Flex, Separator, Button } from "@radix-ui/themes";
import { TRPCReactProvider } from "~/trpc/react";
import { Footer } from "./_components/Footer";
import { Header } from "./_components/Header";
import { HydrateClient } from "~/trpc/server";
import { Sidebar } from "./_components/Sidebar";
import { ThemeProvider } from "next-themes";
import { getServerAuthSession } from "~/server/auth";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerAuthSession();
  return (
    <html suppressHydrationWarning lang="en">
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <HydrateClient>
            <ThemeProvider attribute="class">
              <Theme className="bg-base-100">
                <Flex direction={"column"} className="min-h-screen">
                  <Flex className="flex-1">
                    <Sidebar loggedIn={session !== null} />
                    <Flex className="flex-grow" direction="column">
                      <Header />
                      <Box className="flex-1 mr-5">{children}</Box>
                    </Flex>
                  </Flex>

                  <Separator size="4" className="bg-base-300" />
                  <Footer />
                </Flex>
              </Theme>
            </ThemeProvider>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
