import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Theme, Box, Flex, Separator, Button } from "@radix-ui/themes";
import { TRPCReactProvider } from "~/trpc/react";
import { Footer } from "./_components/Footer";
import { Header } from "./_components/Header";
import { HydrateClient } from "~/trpc/server";
import { Sidebar } from "./_components/Sidebar";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={GeistSans.className}>
        <TRPCReactProvider>
          <HydrateClient>
            <ThemeProvider attribute="class">
              <Theme className="bg-base-100">
                <Flex style={{ minHeight: "100vh" }} direction="column">
                  <Header />
                  <Flex className="flex-1" gap={"4"}>
                    <Sidebar />
                    <Box className="flex-1">{children}</Box>
                  </Flex>
                  <Separator size="4" className="bg-base-300" />
                  <Footer />
                </Flex>
              </Theme>
            </ThemeProvider>
          </HydrateClient>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
